import axios from "axios";


const PI_Services = axios.create({
    baseURL: 'https://ig.gov-cloud.ai/pi-entity-instances-service/v2.0/schemas/',
    headers: {
        Authorization: `Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3Ny1NUVdFRTNHZE5adGlsWU5IYmpsa2dVSkpaWUJWVmN1UmFZdHl5ejFjIn0.eyJleHAiOjE3MjYxODIzMzEsImlhdCI6MTcyNjE0NjMzMSwianRpIjoiOGVlZTU1MDctNGVlOC00NjE1LTg3OWUtNTVkMjViMjQ2MGFmIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLmtleWNsb2FrLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmNzFmMzU5My1hNjdhLTQwYmMtYTExYS05YTQ0NjY4YjQxMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJIT0xBQ1JBQ1kiLCJzZXNzaW9uX3N0YXRlIjoiYmI1ZjJkMzktYTQ3ZC00MjI0LWFjZGMtZTdmNzQwNDc2OTgwIiwibmFtZSI6ImtzYW14cCBrc2FteHAiLCJnaXZlbl9uYW1lIjoia3NhbXhwIiwiZmFtaWx5X25hbWUiOiJrc2FteHAiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJwYXNzd29yZF90ZW5hbnRfa3NhbXhwQG1vYml1c2R0YWFzLmFpIiwiZW1haWwiOiJwYXNzd29yZF90ZW5hbnRfa3NhbXhwQG1vYml1c2R0YWFzLmFpIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7IkhPTEFDUkFDWSI6eyJyb2xlcyI6WyJIT0xBQ1JBQ1lfVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiYmI1ZjJkMzktYTQ3ZC00MjI0LWFjZGMtZTdmNzQwNDc2OTgwIiwidGVuYW50SWQiOiJmNzFmMzU5My1hNjdhLTQwYmMtYTExYS05YTQ0NjY4YjQxMGQiLCJyZXF1ZXN0ZXJUeXBlIjoiVEVOQU5UIn0=.FXeDyHBhlG9L4_NCeSyHEaNEBVmhFpfSBqlcbhHaPaoydhKcA0BfuyHgxg_32kQk6z5S9IQ7nVKS2ybtOvwo0WyLWwLQchSq7Noa7LooHIMzmeWMQb_bLKtbaOti59zwIdS8CkfGaXut7RUQKISQVWmbUGsVJQa2JkG6Ng_QN0y5hFVksMWPZiXVsofQkJXHXV1CQ3gabhhHKo3BqlJwzpsCKLDfg1-4PmSl1Wqbw03Ef2yolroj5i8FoeHukOQPkwCUHrrNw-ilIp917nqZa89YbCMtDjWyaj8pEH7GJR5vMZPE2WcJPn5dSA1IHVunfatEB1cDAitaFjVNWNnddQ`,
        "Content-Type": "application/json",
    },
    
})

const FAB_Services = axios.create({
    baseURL: 'https://ig.gov-cloud.ai/fab-backend/llm',
     headers: {
        Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3Ny1NUVdFRTNHZE5adGlsWU5IYmpsa2dVSkpaWUJWVmN1UmFZdHl5ejFjIn0.eyJleHAiOjE3MjYxODIzMzEsImlhdCI6MTcyNjE0NjMzMSwianRpIjoiOGVlZTU1MDctNGVlOC00NjE1LTg3OWUtNTVkMjViMjQ2MGFmIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLmtleWNsb2FrLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmNzFmMzU5My1hNjdhLTQwYmMtYTExYS05YTQ0NjY4YjQxMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJIT0xBQ1JBQ1kiLCJzZXNzaW9uX3N0YXRlIjoiYmI1ZjJkMzktYTQ3ZC00MjI0LWFjZGMtZTdmNzQwNDc2OTgwIiwibmFtZSI6ImtzYW14cCBrc2FteHAiLCJnaXZlbl9uYW1lIjoia3NhbXhwIiwiZmFtaWx5X25hbWUiOiJrc2FteHAiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJwYXNzd29yZF90ZW5hbnRfa3NhbXhwQG1vYml1c2R0YWFzLmFpIiwiZW1haWwiOiJwYXNzd29yZF90ZW5hbnRfa3NhbXhwQG1vYml1c2R0YWFzLmFpIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7IkhPTEFDUkFDWSI6eyJyb2xlcyI6WyJIT0xBQ1JBQ1lfVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiYmI1ZjJkMzktYTQ3ZC00MjI0LWFjZGMtZTdmNzQwNDc2OTgwIiwidGVuYW50SWQiOiJmNzFmMzU5My1hNjdhLTQwYmMtYTExYS05YTQ0NjY4YjQxMGQiLCJyZXF1ZXN0ZXJUeXBlIjoiVEVOQU5UIn0=.FXeDyHBhlG9L4_NCeSyHEaNEBVmhFpfSBqlcbhHaPaoydhKcA0BfuyHgxg_32kQk6z5S9IQ7nVKS2ybtOvwo0WyLWwLQchSq7Noa7LooHIMzmeWMQb_bLKtbaOti59zwIdS8CkfGaXut7RUQKISQVWmbUGsVJQa2JkG6Ng_QN0y5hFVksMWPZiXVsofQkJXHXV1CQ3gabhhHKo3BqlJwzpsCKLDfg1-4PmSl1Wqbw03Ef2yolroj5i8FoeHukOQPkwCUHrrNw-ilIp917nqZa89YbCMtDjWyaj8pEH7GJR5vMZPE2WcJPn5dSA1IHVunfatEB1cDAitaFjVNWNnddQ"
    },
}) 

const FAB_Interactive_Service = axios.create({
    baseURL:"https://ig.gov-cloud.ai/agent-orchestration-framework-fastapi/agent",
    headers: {
        Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJKZTNYVjhSWHI0SzFWZmRWTjJ2ejFVMTZPWGRZaUFENWdEaDREc1RuNlRnIn0.eyJleHAiOjE3MjI0NTk5MDMsImlhdCI6MTcyMjQyMzkwMywianRpIjoiODJiZGE3ZDktNDJhYi00NGIxLTliNmMtMTkxMzk4ZmRmNzRlIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOlsidGVzdEN1c3RvbTEiLCJ0ZXN0Q3VzdG9tMiIsImFjY291bnQiXSwic3ViIjoiODliZWRhNzQtODU5Mi00NWZlLThmZGQtMWZkOWEzNWRjYTgzIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiSE9MQUNSQUNZIiwic2Vzc2lvbl9zdGF0ZSI6IjBkNzdmN2IzLTgxZDMtNDQzMi05NmZmLWE3YTg4NWRmZWExNCIsIm5hbWUiOiJkamRrIHRlc3QxIiwiZ2l2ZW5fbmFtZSI6ImRqZGsiLCJmYW1pbHlfbmFtZSI6InRlc3QxIiwicHJlZmVycmVkX3VzZXJuYW1lIjoicGFzc3dvcmRfdGVuYW50X2NmY2ZAZ2F0ZXN0YXV0b21hdGlvbi5jb20iLCJlbWFpbCI6InBhc3N3b3JkX3RlbmFudF9jZmNmQGdhdGVzdGF1dG9tYXRpb24uY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InRlc3RDdXN0b20xIjp7InJvbGVzIjpbInRlc3QyIiwidGVzdDMiLCJ0ZXN0MSJdfSwidGVzdEN1c3RvbTIiOnsicm9sZXMiOlsidGVzdDIiLCJ0ZXN0MyIsInRlc3QxIl19LCJIT0xBQ1JBQ1kiOnsicm9sZXMiOlsiSE9MQUNSQUNZX1VTRVIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjBkNzdmN2IzLTgxZDMtNDQzMi05NmZmLWE3YTg4NWRmZWExNCIsInRlbmFudElkIjoiODliZWRhNzQtODU5Mi00NWZlLThmZGQtMWZkOWEzNWRjYTgzIiwicmVxdWVzdGVyVHlwZSI6IlRFTkFOVCJ9.g3gS5jWPo1iqn1Ytkk3ETiuN1D5RgqByBOd8u55EzxhmvuhoVIrJdUWZOBOaplB-5hzAk4dPQNRkDkgYFVaLCMRUihK9Y-tGgdBbPVZwaXkidaEHaoM81djNfVhY3J5KlOBNn2lH4Deh3lHVYvF7aO-KmL0ECBuaaltO9gqDc5xSzwy7U58sT-ONxL_yP-AUkB5CN2g6HMhxt2-cPFodbjSnNyeO00Ri7GastHfr8ZK-3zW25oDwshk87osAvWsfI6qcR3RwFRdXX_cwBEU0x9CRVVOsngGr4VbM3uFXpROM12tYHqrPIptEgKB4VVlGd-GUF-vSC7Sw5v1lEcOwdg",
        "Content-Type": "application/json",
    },
})

const Mobius_Iam_Service = axios.create({
    baseURL:"https://ig.gov-cloud.ai/mobius-iam-service/v1.0/emails",
    headers: {
        Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImZmOGYxNjhmLTNmZjYtNDZlMi1iMTJlLWE2YTdlN2Y2YTY5MCJ9.eyJwcm9maWxlVXJsIjoiIiwicmVjZW50X3Nlc3Npb24iOiJOQSIsInN1YiI6ImdhaWFuLmNvbSIsInBhcmVudFRlbmFudElkIjoiTkEiLCJjb2xvciI6IkJsYWNrIiwidXNlcl9uYW1lIjoiZ2FpYW4iLCJpc3MiOiJnYWlhbi5jb20iLCJpc0FkbWluIjp0cnVlLCJwbGF0Zm9ybUlkIjoiNjRlMjA4MDUzOGM5NDk3YzFmZThlMjdlIiwidXNlck5hbWUiOiJnYWlhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfTUFSS0VUUExBQ0VfVVNFUiJdLCJjbGllbnRfaWQiOiJnYWlhbiIsInNjb3BlIjpbInRydXN0IiwicmVhZCIsIndyaXRlIl0sInRlbmFudElkIjoiNjE4YjZmZGVmNWRhY2MwMDAxYTZiMWIwIiwibG9nbyI6Ind3dy5nb29nbGUuY29tL2ltYWdlcy4iLCJleHAiOjE3MDU1MTc2NDEsImp0aSI6IjJhNjM4OGI1LTg0MzEtNDAwYy1iMzkzLTA1ZDFkYjcxMjIyZiIsImVtYWlsIjoibW9iaXVzQGdhaWFuc29sdXRpb25zLmNvbSJ9.XpGvosExlvzNJrLjeHwsXJvqKcukHJ0TfD7Howmoqi35t6_L13VqcuuoadWotoMkWZpWVfyx3tg8OBrMfnbsHiFU_SCpS9gTIQU4CgjecRgqoezYI6e6oIog4viWArtEQrMgi5RdglYhoKm4NN3s9ooU4gmLJmJrovboNWD9gWDyYR7-YYlsybDxDRjO_SE-jt6vdsR-MUcii4ozkaMNabRf1_pPxpg2pDpCvMZXAek4lUf7_w-rGHzkHa_0xMGTLaQkzUpHy6baKQspgpJp-f9--8J4wwGu187II0sp-Qb5dkpxku635QXfVP0mNO4UEKX8yXx6WKDz0IAjz64Jtw",
        "Content-Type": "application/json",
    },
})

const Mobius_Content_Service = axios.create({
    baseURL:"https://ig.gov-cloud.ai/mobius-content-service/v1.0/content",
    headers: {
        Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3Ny1NUVdFRTNHZE5adGlsWU5IYmpsa2dVSkpaWUJWVmN1UmFZdHl5ejFjIn0.eyJleHAiOjE3MjYxODIzMzEsImlhdCI6MTcyNjE0NjMzMSwianRpIjoiOGVlZTU1MDctNGVlOC00NjE1LTg3OWUtNTVkMjViMjQ2MGFmIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrLmtleWNsb2FrLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmNzFmMzU5My1hNjdhLTQwYmMtYTExYS05YTQ0NjY4YjQxMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJIT0xBQ1JBQ1kiLCJzZXNzaW9uX3N0YXRlIjoiYmI1ZjJkMzktYTQ3ZC00MjI0LWFjZGMtZTdmNzQwNDc2OTgwIiwibmFtZSI6ImtzYW14cCBrc2FteHAiLCJnaXZlbl9uYW1lIjoia3NhbXhwIiwiZmFtaWx5X25hbWUiOiJrc2FteHAiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJwYXNzd29yZF90ZW5hbnRfa3NhbXhwQG1vYml1c2R0YWFzLmFpIiwiZW1haWwiOiJwYXNzd29yZF90ZW5hbnRfa3NhbXhwQG1vYml1c2R0YWFzLmFpIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7IkhPTEFDUkFDWSI6eyJyb2xlcyI6WyJIT0xBQ1JBQ1lfVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiYmI1ZjJkMzktYTQ3ZC00MjI0LWFjZGMtZTdmNzQwNDc2OTgwIiwidGVuYW50SWQiOiJmNzFmMzU5My1hNjdhLTQwYmMtYTExYS05YTQ0NjY4YjQxMGQiLCJyZXF1ZXN0ZXJUeXBlIjoiVEVOQU5UIn0=.FXeDyHBhlG9L4_NCeSyHEaNEBVmhFpfSBqlcbhHaPaoydhKcA0BfuyHgxg_32kQk6z5S9IQ7nVKS2ybtOvwo0WyLWwLQchSq7Noa7LooHIMzmeWMQb_bLKtbaOti59zwIdS8CkfGaXut7RUQKISQVWmbUGsVJQa2JkG6Ng_QN0y5hFVksMWPZiXVsofQkJXHXV1CQ3gabhhHKo3BqlJwzpsCKLDfg1-4PmSl1Wqbw03Ef2yolroj5i8FoeHukOQPkwCUHrrNw-ilIp917nqZa89YbCMtDjWyaj8pEH7GJR5vMZPE2WcJPn5dSA1IHVunfatEB1cDAitaFjVNWNnddQ"
    },
})

const endpoint = `/instances/list?size=2000&showPageableMetaData=true&showDBaaSReservedKeywords=false`;
const body = { dbType: "TIDB" };

export async function PostNewApplcation(schemaID) {
    const data= await PI_Services.post(`${schemaID}${endpoint}`,body);
    return await data.data
}

export async function PostKYCScreening(schemaID){
    const data= await PI_Services.post(`${schemaID}${endpoint}`,body)
    return await data.data
}

export async function PostApplicationStatus(schemaID){
    const data=await PI_Services.post(`${schemaID}${endpoint}`,body)
    return await data.data
}
export async function PostComplianceCheck(schemaID){
    const data=await PI_Services.post(`${schemaID}${endpoint}`,body)
    return await data.data
}

export async function PostAuditTrails(schemaID){
    const data=await PI_Services.post(`${schemaID}${endpoint}`,body)
    return await data.data
}

export async function PostFabDocs(endpoint,docData){
    const data=await FAB_Services.post(endpoint,docData)
    return await data.data
}

export async function PostSchema(endpoint,reqBody){
    const data=await PI_Services.post(endpoint,reqBody)
    return await data.data
}

export async function PostInteractive(endpoint,payload){
    let body = payload;
    const data=await FAB_Interactive_Service.post(endpoint,body)
    return await data.data
}

export async function OTPApi(endpoint,payload){
    let body = payload;
    const data=await Mobius_Iam_Service.post(endpoint,body)
    return await data.data
}

export async function UploadFiles(endpoint,payload){
    const data=await Mobius_Content_Service.post(endpoint,payload)
    return await data.data
}